### ISSUE TITLE
【需求】：支持下载图片结果，并与预置图包做图像比对

### ISSUE THREAD

**Issue by Catmint103** [x-bell/xbell#1]
1.支持触发图片下载zip文件的解压；
2.zip包解压后每张图与预置图包内对应图片做图像比对；
3.支持设置图像对比相似度百分比，比如入参95，代表低于95%相似度返回false；

**Comment by xlianghang** [comment]
版本：xbell@0.3.4
参考这里哈：[快照测试](https://x-bell.github.io/xbell/docs/snapshot)

**Comment by xlianghang** [comment]
下载的方案，我下周提供一下~
