### ISSUE TITLE
【需求】：支持登录API，可配置登录环境、接口，通过账号密码登录

### ISSUE THREAD

**Issue by Catmint103** [x-bell/xbell#5]
1. 支持登录API，可配置登录环境、接口，通过账号密码登录
2. 获取token并同步到无头浏览器local storage
3. 支持清理token（或退出登录清理token）

**Comment by xlianghang** [comment]
version: xbell@0.3.4

参考这个 [demo](https://x-bell.github.io/xbell/docs/diy-decorator#%E9%80%9A%E8%BF%87-api-%E5%BF%AB%E9%80%9F%E7%99%BB%E5%BD%95)

每个 case 是独立的浏览器上下文，刚启动时不会携带其它case 的token~
